// Resource bindings are generated by `wrangler types`; secrets are installed at deployment.
export type AppEnv = {
  [K in keyof Cloudflare.Env]: NonNullable<Cloudflare.Env[K]> extends string
    ? string
    : Cloudflare.Env[K];
} & {
  SUPABASE_SERVICE_ROLE_KEY?: string;
  CREDENTIAL_ENCRYPTION_KEY?: string;
  SLACK_CLIENT_SECRET?: string;
  ADMIN_USER_IDS?: string;
  API_ORIGIN?: string;
  MCP_ENABLED?: string;
  VIEW_HASH_KEY?: string;
  GITHUB_APP_ID?: string;
  GITHUB_INSTALLATION_ID?: string;
  GITHUB_APP_PRIVATE_KEY?: string;
};
