// Resource bindings are generated by `wrangler types`; secrets are installed at deployment.
export type AppEnv = {
  [K in keyof Cloudflare.Env]: Cloudflare.Env[K] extends string
    ? string
    : Cloudflare.Env[K];
} & {
  SUPABASE_SERVICE_ROLE_KEY?: string;
  CREDENTIAL_ENCRYPTION_KEY?: string;
  SLACK_CLIENT_SECRET?: string;
  ADMIN_USER_IDS?: string;
};
